(source gnu)
(source marmalade)
(source melpa)
(source org)

(depends-on "ace-jump-mode")
(depends-on "ag")
(depends-on "cask")
(depends-on "clojure-mode")
(depends-on "expand-region")
(depends-on "flx-ido")
(depends-on "groovy-mode")
(depends-on "highlight-chars")
(depends-on "ido-at-point")
(depends-on "ido-vertical-mode")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "soft-charcoal-theme")